name: Push on CI branch

on:
  push:
    branches:
      - ci

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./task-api

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: task
#        options:
#          --health-cmd mongo
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - run: |
          pnpm install
          pnpm run build
          & pnpm run start:prod

        env:
          MONGO_URL: mongodb://root:task@localhost
          insecure: true
          JAEGER_URL: "http://localhost:4318/v1/traces"
          HEALTH_PORT: 3003
          AUTH_API_URL: "localhost:4002"
          PORT: 5004

      - name: setup golang
        uses: actions/setup-go@v4
        with:
            go-version: 1.20

      - run: |
          cd test
          go mod download
          go test
